spring.datasource.url=jdbc:postgresql://localhost:5432/liquibasedb
spring.datasource.username=liquibase
spring.datasource.password=liquibase
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
