spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/preprod_database
    username: preprod_user
    password: preprod_pass
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: preprod